[tool.poetry]
name = "medical-study-chatgpt"
version = "0.1.0"
description = "A Streamlit application for medical study assistance using ChatGPT."
authors = ["Felix Fricke <f.fricke@tum.de>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.42.2"
openai = "^1.65.1"
streamlit-chat = "^0.1.1"
python-dotenv = "^1.1.0"
markdown-pdf = "^1.6"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
